# Generated by Django 5.2.8 on 2025-11-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
